//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.WebControls;
namespace MAPS {
    
    
    public partial class GazetteDetail1 {

        protected Button btnClick;

        protected Label lblZone;

        protected Label lblCircle;

        protected Label lblDivision;

        protected Label lblBlcok;

        protected Label lblVillage;

        protected Label lblForestType;

        protected TextBox txtNotificationNumber;

        protected TextBox txtNotificationType;

        protected TextBox txtGazetteDate;

        protected TextBox txtGazetteNo;

        protected TextBox txtGazetteAuthority;

        protected TextBox txtGazetteTitle;

        protected TextBox txtEnglishPage;

        protected TextBox txtHindiPage;

        protected Button btnSubmit;

        protected GridView gvShow;

        protected Button btnSave;
    }
}
